### ISSUE TITLE
loading "most popular" takes alot of time

### ISSUE THREAD

**Issue by meijin007** [i96751414/plugin.video.pulsar#4]
worse then the last version (so called "0.6.2")

**Comment by meijin007** [comment]
LOG:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Pyth
on callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO M
EMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPErro
r'>
                                            Error Contents: HTTP Error 500: Inte
rnal Server Error
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/p
lugin.video.pulsar/navigation.py", line 6, in <module>
                                                navigation.run()
                                              File "/var/lib/kodi/.kodi/addons/p
lugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 87, in ru
n
                                                data = _json(url)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/navigation.py", line 46, in _json
                                                with closing(urllib2.urlopen(url)) as response:
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 500: Internal Server Error
                                            -->End of Python script error report<--
20:06:29 T:1950474240   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/movies/popular
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] 192.168.1.101
20:06:29 T:1950474240   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/movies/popular) failed
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] 2016/01/24 18:06:29 Panic recovery -> runtime error: invalid memory address or nil pointer dereference
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /usr/local/go-go1.6beta2/src/runtime/panic.go:426 (0x1002fc)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /usr/local/go-go1.6beta2/src/runtime/panic.go:45 (0xfe9d0)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /usr/local/go-go1.6beta2/src/runtime/sigpanic_unix.go:24 (0x116420)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/i96751414/pulsar/tmdb/movie.go:289 (0x32b0c4)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/i96751414/pulsar/api/movies.go:80 (0x1f3d70)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/i96751414/pulsar/api/movies.go:110 (0x1f4a60)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/context.go:95 (0x30fc44)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/i96751414/pulsar/cache/cache.go:114 (0x353750)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/context.go:95 (0x30fc44)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/logger.go:56 (0x31ef60)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/context.go:95 (0x30fc44)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/recovery.go:43 (0x31f864)
20:06:29 T:1481667456  NOTICE: [plugin.video.pulsar] /home/ze/Go/src/github.com/gin-gonic/gin/context.go:95 (0x30fc44)

**Comment by i96751414** [comment]
Please tell me something, do you have pagination enabled?

**Comment by meijin007** [comment]
No

**Comment by i96751414** [comment]
Could you enable it and clear cache please? I implemented pagination exactly because of that. Without pagination Pulsar searches a lot of movies (>300) and it takes a lot of time, originating some timeouts from plugin.video.pulsar.

**Comment by meijin007** [comment]
after enabling paging problem seems to be solved. what so ever, I think there should be better exception handling about this time out.

**Comment by i96751414** [comment]
I see too possible ways to solve it:
1 - Increase timeout so it wont fail on some users
2 - Decrease the number of movies to search (so the search time will decrease)

Pick one

**Comment by meijin007** [comment]
anther idea, for better exception handling:
if it reach time out, it will do paging, for not crashing, with some notification to the user.

**Comment by i96751414** [comment]
The problem is that pulsar saves everything to cache, so pagination won't help (because the timeout was on plugin.video.pulsar side. The Daemon's side already saved the results on cache)

**Comment by meijin007** [comment]
so i think 2 is the better options.
